# Meta data for each book.
# Is primarily used to display static information on the frontend without
# needing to make database calls.

# fmt: off
old_testament = {
    "genesis": {"book_no": 1, "book": "Genesis", "url": "genesis", "chapters": 50},
    "exodus": {"book_no": 2, "book": "Exodus", "url": "exodus", "chapters": 40},
    "leviticus": {"book_no": 3, "book": "Leviticus", "url": "leviticus", "chapters": 27},
    "numbers": {"book_no": 4, "book": "Numbers", "url": "numbers", "chapters": 36},
    "deuteronomy": {"book_no": 5, "book": "Deuteronomy", "url": "deuteronomy", "chapters": 34},
    "joshua": {"book_no": 6, "book": "Joshua", "url": "joshua", "chapters": 24},
    "judges": {"book_no": 7, "book": "Judges", "url": "judges", "chapters": 21},
    "ruth": {"book_no": 8, "book": "Ruth", "url": "ruth", "chapters": 4},
    "1-samuel": {"book_no": 9, "book": "1 Samuel", "url": "1-samuel", "chapters": 31},
    "2-samuel": {"book_no": 10, "book": "2 Samuel", "url": "2-samuel", "chapters": 24},
    "1-kings": {"book_no": 11, "book": "1 Kings", "url": "1-kings", "chapters": 22},
    "2-kings": {"book_no": 12, "book": "2 Kings", "url": "2-kings", "chapters": 25},
    "1-chronicles": {"book_no": 13, "book": "1 Chronicles", "url": "1-chronicles", "chapters": 29},
    "2-chronicles": {"book_no": 14, "book": "2 Chronicles", "url": "2-chronicles", "chapters": 36},
    "ezra": {"book_no": 15, "book": "Ezra", "url": "ezra", "chapters": 10},
    "nehemiah": {"book_no": 16, "book": "Nehemiah", "url": "nehemiah", "chapters": 13},
    "esther": {"book_no": 17, "book": "Esther", "url": "esther", "chapters": 10},
    "job": {"book_no": 18, "book": "Job", "url": "job", "chapters": 42},
    "psalms": {"book_no": 19, "book": "Psalms", "url": "psalms", "chapters": 150},
    "proverbs": {"book_no": 20, "book": "Proverbs", "url": "proverbs", "chapters": 31},
    "ecclesiastes": {"book_no": 21, "book": "Ecclesiastes", "url": "ecclesiastes", "chapters": 12},
    "song-of-solomon": {"book_no": 22, "book": "Song of Solomon", "url": "song-of-solomon", "chapters": 8},
    "isaiah": {"book_no": 23, "book": "Isaiah", "url": "isaiah", "chapters": 66},
    "jeremiah": {"book_no": 24, "book": "Jeremiah", "url": "jeremiah", "chapters": 52},
    "lamentations": {"book_no": 25, "book": "Lamentations", "url": "lamentations", "chapters": 5},
    "ezekiel": {"book_no": 26, "book": "Ezekiel", "url": "ezekiel", "chapters": 48},
    "daniel": {"book_no": 27, "book": "Daniel", "url": "daniel", "chapters": 12},
    "hosea": {"book_no": 28, "book": "Hosea", "url": "hosea", "chapters": 14},
    "joel": {"book_no": 29, "book": "Joel", "url": "joel", "chapters": 3},
    "amos": {"book_no": 30, "book": "Amos", "url": "amos", "chapters": 9},
    "obadiah": {"book_no": 31, "book": "Obadiah", "url": "obadiah", "chapters": 1},
    "jonah": {"book_no": 32, "book": "Jonah", "url": "jonah", "chapters": 4},
    "micah": {"book_no": 33, "book": "Micah", "url": "micah", "chapters": 7},
    "nahum": {"book_no": 34, "book": "Nahum", "url": "nahum", "chapters": 3},
    "habakkuk": {"book_no": 35, "book": "Habakkuk", "url": "habakkuk", "chapters": 3},
    "zephaniah": {"book_no": 36, "book": "Zephaniah", "url": "zephaniah", "chapters": 3},
    "haggai": {"book_no": 37, "book": "Haggai", "url": "haggai", "chapters": 2},
    "zechariah": {"book_no": 38, "book": "Zechariah", "url": "zechariah", "chapters": 14},
    "malachi": {"book_no": 39, "book": "Malachi", "url": "malachi", "chapters": 4}
}

new_testament = {
    "matthew": {"book_no": 40, "book": "Matthew", "url": "matthew", "chapters": 28},
    "mark": {"book_no": 41, "book": "Mark", "url": "mark", "chapters": 16},
    "luke": {"book_no": 42, "book": "Luke", "url": "luke", "chapters": 24},
    "john": {"book_no": 43, "book": "John", "url": "john", "chapters": 21},
    "acts": {"book_no": 44, "book": "Acts", "url": "acts", "chapters": 28},
    "romans": {"book_no": 45, "book": "Romans", "url": "romans", "chapters": 16},
    "1-corinthians": {"book_no": 46, "book": "1 Corinthians", "url": "1-corinthians", "chapters": 16},
    "2-corinthians": {"book_no": 47, "book": "2 Corinthians", "url": "2-corinthians", "chapters": 13},
    "galatians": {"book_no": 48, "book": "Galatians", "url": "galatians", "chapters": 6},
    "ephesians": {"book_no": 49, "book": "Ephesians", "url": "ephesians", "chapters": 6},
    "philippians": {"book_no": 50, "book": "Philippians", "url": "philippians", "chapters": 4},
    "colossians": {"book_no": 51, "book": "Colossians", "url": "colossians", "chapters": 4},
    "1-thessalonians": {"book_no": 52, "book": "1 Thessalonians", "url": "1-thessalonians", "chapters": 5},
    "2-thessalonians": {"book_no": 53, "book": "2 Thessalonians", "url": "2-thessalonians", "chapters": 3},
    "1-timothy": {"book_no": 54, "book": "1 Timothy", "url": "1-timothy", "chapters": 6},
    "2-timothy": {"book_no": 55, "book": "2 Timothy", "url": "2-timothy", "chapters": 4},
    "titus": {"book_no": 56, "book": "Titus", "url": "titus", "chapters": 3},
    "philemon": {"book_no": 57, "book": "Philemon", "url": "philemon", "chapters": 1},
    "hebrews": {"book_no": 58, "book": "Hebrews", "url": "hebrews", "chapters": 13},
    "james": {"book_no": 59, "book": "James", "url": "james", "chapters": 5},
    "1-peter": {"book_no": 60, "book": "1 Peter", "url": "1-peter", "chapters": 5},
    "2-peter": {"book_no": 61, "book": "2 Peter", "url": "2-peter", "chapters": 3},
    "1-john": {"book_no": 62, "book": "1 John", "url": "1-john", "chapters": 5},
    "2-john": {"book_no": 63, "book": "2 John", "url": "2-john", "chapters": 1},
    "3-john": {"book_no": 64, "book": "3 John", "url": "3-john", "chapters": 1},
    "jude": {"book_no": 65, "book": "Jude", "url": "jude", "chapters": 1},
    "revelation": {"book_no": 66, "book": "Revelation", "url": "revelation", "chapters": 22}
}
# fmt: on
